# Implement your install deployment tasks here
# -------------------------------------------------

- name: wait for backstage application to sync
  k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: backstage
    namespace: openshift-gitops
  register: r_application
  retries: 180
  delay: 10
  until:
  - r_application.resources | length > 0
  - r_application.resources[0].status is defined
  - r_application.resources[0].status.sync is defined
  - r_application.resources[0].status.sync.status is defined
  - r_application.resources[0].status.sync.status == 'Synced'

- name: wait for backstage pod to be ready
  k8s_info:
    #api_version: argoproj.io/v1alpha1
    kind: Deployment
    name: backstage-developer-hub
    namespace: backstage
  register: r_deployment
  retries: 180
  delay: 10
  until:
  - r_deployment.resources | length > 0
  - r_deployment.resources[0].status is defined
  - r_deployment.resources[0].status.readyReplicas is defined
  - r_deployment.resources[0].status.readyReplicas > 0

- name: wait a bit
  pause:
    seconds: 120

- name: scale backstage application to zero
  shell: oc scale deployment/backstage-developer-hub --replicas=0 -n backstage

- name: disable gitops sync
  shell: |
    oc patch apps backstage-gitops -n openshift-gitops --type=json -p '[{"op": "remove", "path": "/spec/syncPolicy/automated"}]'
    oc patch apps backstage -n openshift-gitops --type=json -p '[{"op": "remove", "path": "/spec/syncPolicy/automated"}]'
  ignore_errors: true

- name: create backstage config file
  template:
    src: "templates/app-config.yaml.j2"
    dest: "/tmp/app-config.yaml"

- name: replace backstage configmap
  shell: |
    oc delete configmap backstage-developer-hub-app-config -n backstage
    oc create configmap backstage-developer-hub-app-config --from-file=/tmp/app-config.yaml -n backstage
    oc label --overwrite configmap backstage-developer-hub-app-config rht-gitops.com/openshift-gitops=backstage -n backstage

- name: create dynamic-plugins config file
  template:
    src: "templates/dynamic-plugins.yaml.j2"
    dest: "/tmp/dynamic-plugins.yaml"

- name: replace dynamic-plugins configmap
  shell: |
    oc delete configmap backstage-dynamic-plugins -n backstage
    oc create configmap backstage-dynamic-plugins --from-file=/tmp/dynamic-plugins.yaml -n backstage
    oc label --overwrite configmap backstage-dynamic-plugins rht-gitops.com/openshift-gitops=backstage -n backstage

#- name: start backstage re-deployment
#  shell: |
#    oc delete pods --selector=app.kubernetes.io/name=developer-hub -n backstage

- name: re-start backstage application
  shell: oc scale deployment/backstage-developer-hub --replicas=1 -n backstage